### ISSUE TITLE
Configuring a FreeBSD VM.

### ISSUE THREAD

**Issue by mzs114** [ployground/bsdploy#80]
After bootstrapping I am trying to configure a FreeBSD VM on virtualbox, I am not following quick start guide.
So we can consider the VM as a plain instance.

```
% ploy configure jailhost
WARNING: You are using an untested version 1.9.1 of ansible. The latest tested version is 1.8.X. Any errors may be caused by that newer version.
WARNING: You are using an untested version 1.9.1 of ansible. The latest tested version is 1.8.X. Any errors may be caused by that newer version.

PLAY [jailhost] *************************************************************** 

GATHERING FACTS *************************************************************** 
fatal: [jailhost] => Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/ansible/runner/__init__.py", line 582, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/local/lib/python2.7/site-packages/ansible/runner/__init__.py", line 785, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/local/lib/python2.7/site-packages/ansible/runner/__init__.py", line 964, in _executor_internal_inner
    conn = self.connector.connect(actual_host, actual_port, actual_user, actual_pass, actual_transport, actual_private_key_file, delegate_host)
TypeError: connect_patch() takes exactly 7 arguments (8 given)


TASK: [jails_host | bind host sshd to primary ip] ***************************** 
FATAL: no hosts matched or all hosts have already failed -- aborting
```

Following is the content of ploy.conf

```
[ez-master:jailhost]
ip = 192.168.56.101
#bootstrap-fingerprint = 9e:5a:5d:3f:52:a3:bf:2b:6e:a0:34:f7:e5:20:11:af
#bootstrap-system-devices = ada0
#bootstrap-swap-size = 1
http_proxy = http://vlabcse:vlabcse@202.141.80.30:3128/
#instance = jail1
roles =
   jails_host

#[instance:jail1]
#master = jailhost
#ip = 172.16.0.1
```
Is this because of newer version of Ansible?

**Comment by fschulze** [comment]
Yes, installing ploy_ansible 1.3.0 should fix that, or downgrading ansible to 1.8.x.

**Comment by mzs114** [comment]
ok, I got the new version of ploy_ansible installed.

```
% pkg info py27-ploy_ansible-1.3.0
py27-ploy_ansible-1.3.0
Name           : py27-ploy_ansible
Version        : 1.3.0
```
That was on the client.
The target is a new stock installed FreeBSD on a new VM. On which I installed python2.7, copied the ssh public keys and I am able ssh without password.

But ploy ssh , configure fails.

```
% ploy configure jailhost

PLAY [jailhost] *************************************************************** 

GATHERING FACTS *************************************************************** 
ERROR: Failed to connect to plain-instance:jailhost (192.168.56.110)
ERROR: username: 'root'
ERROR: port: 22
fatal: [jailhost] => Couldn't validate fingerprint for 'ez-master:jailhost': No fingerprint set in config.

TASK: [jails_host | bind host sshd to primary ip] ***************************** 
FATAL: no hosts matched or all hosts have already failed -- aborting


% ploy ssh jailhost
ERROR: Failed to connect to plain-instance:jailhost (192.168.56.110)
ERROR: username: 'root'
ERROR: port: 22
ERROR: Couldn't validate fingerprint for ssh connection.
ERROR: No fingerprint set in config.
ERROR: Is the instance finished starting up?
```
I copied RSA fingerprint in the config, the finger print is of the target FreeBSD VM.
I also tried copying the ECDSA finger print, it failed both times.

```
cat etc/ploy.conf 

[ez-master:jailhost]
ip = 192.168.56.110
user = root
http_proxy = http://proxy.iiit.ac.in:8080/
bootstrap-fingerprint = d3:60:de:16:94:84:3f:47:7e:aa:c8:32:0c:79:f4:4f
roles = 
 jails_host


ssh-keygen -l -f ~/.ssh/known_hosts
..
2048 d3:60:de:16:94:84:3f:47:7e:aa:c8:32:0c:79:f4:4f fbsd (RSA)
```

**Comment by mzs114** [comment]
Ok, solved it using ploy documentation https://github.com/ployground/ploy

I first removed the passphrase on the private key, thinking this might solve it.
Then set `ssh-key-filename`, still no go.
Finally observed that there is one more option `fingerprint`, set it to `ignore` and it allowed me to ssh.

The final `ploy.conf` as it is now:

```
[ez-master:jailhost]
ip = 192.168.56.110
user = root
http_proxy = http://proxy.iiit.ac.in:8080/
#ssh-key-filename = /home/user/.ssh/id_rsa
fingerprint = 2f:ed:44:0c:1c:21:ef:04:57:86:73:3d:d9:58:b7:68
#bootstrap-fingerprint = d3:60:de:16:94:84:3f:47:7e:aa:c8:32:0c:79:f4:4f
#bootstrap-fingerprint = 2f:ed:44:0c:1c:21:ef:04:57:86:73:3d:d9:58:b7:68
roles =
 jails_host
```

I was hoping that bsdploy would use the fingerprint from `~/.ssh/know_hosts`.

I am concerned that a passphrase protected private key cannot be used.

```
ploy ssh jailhost
ERROR: Failed to connect to plain-instance:jailhost (192.168.56.110)
ERROR: username: 'root'
ERROR: port: 22
ERROR: Private key file is encrypted
ERROR: Is the instance finished starting up?
```

**Comment by fschulze** [comment]
Yes, for an existing server you need to provide the fingerprint, as ploy can't know about it. If you follow the quickstart, the ssh host key is generated before and uploaded to the VM during bootstrap. That's why ploy knows the fingerprint.

Private keys with passphrase do work. The error message is misleading, but not under our control. My ssh key has a passphrase unlocked via my OS X keychain. There might be issues with entering the passphrase if you need a terminal for it, not sure about that, since on OS X I get a dialog popup.

**Comment by mzs114** [comment]
Thanks, I am trying these from a FreeBSD machine.

I am now stuck at this.

```
% ploy configure jailhost

TASK: [jails_host | Setup data zpool] ***************************************** 
failed: [jailhost] => {"failed": true}
msg: Don't know how to handle 0 number of devices ().

FATAL: all hosts have already failed -- aborting
```

The corresponding task in the playbook `jails_host/tasks/main.yml` is:

```
- name: Setup data zpool
  zpool:
    name: "{{ ploy_bootstrap_data_pool_name }}"
    geli: "{{ ploy_bootstrap_geli|bool }}"
    version: "{{ ploy_bootstrap_zpool_version }}"
    devices: "{{ ploy_bootstrap_data_pool_devices }}"
    raid_mode: "{{ ploy_bootstrap_raid_mode }}"
  register: data_pool_result
```
As I am directly configuring without bootstrapping, how do I pass these?

**Comment by fschulze** [comment]
You have to set ``bootstrap-data-pool-name`` to your ZFS pool in ploy.conf. ZFS is a requirement for bsdploy. We normally setup a smaller (~10GB) system partition and use the rest of the hdd as the data pool.

**Comment by mzs114** [comment]
Thank you for bearing with me, I finally got it configured. 
Sent some pull requests on what I think are improvements.
I now need to figure out how to populate the host with jails. I will also contrast this with the bootstrapping process with a mfsBSD image.

A suggestion: listing and describing these internally used options will really help.
I could not find `bootstrap-data-pool-name` anywhere in the documentation.

**Comment by fschulze** [comment]
Yes, the documentation is still behind. We improve it gradually and try to only add new features if they are documented to not fall behind even further.
